---
- name: "Install 'python3-pip' package on swarm managers"
  ansible.builtin.package:
    name: python3-pip
    state: present
    update_cache: true
  when: inventory_hostname in groups['swarm_managers']

- name: "Install 'jsondiff' module on swarm managers"
  ansible.builtin.pip:
    name: jsondiff
  when: inventory_hostname in groups['swarm_managers']

- name: "Init 'Swarm Mode' on the manager."
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ docker_swarm_advertise_addr }}"
  register: result_swarm_values
  when: inventory_hostname in groups['swarm_managers'][0]

- name: "Join worker"
  community.docker.docker_swarm:
    state: join
    timeout: 60
    advertise_addr: "{{ docker_swarm_advertise_addr }}"
    join_token: "{{ hostvars[groups['swarm_managers'][0]]['result_swarm_values']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ docker_swarm_manager_addr }}"
  when: inventory_hostname in groups['swarm_workers']
