---
# tasks file for ansible-role-docker-swarm-init
- name: "Install 'python3-pip' package on swarm managers"
  package:
    name: python3-pip
    state: present
    update_cache: true
  when: inventory_hostname in groups['swarm_manager']

- name: "Install 'jsondiff' module on swarm managers"
  ansible.builtin.pip:
    name: jsondiff
  when: inventory_hostname in groups['swarm_manager']

- name: "Init 'Swarm Mode' on the manager."
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ hostvars[groups['swarm_manager'][0]].ansible_host }}"
  register: result_swarm_values
  when: inventory_hostname in groups['swarm_manager'][0]

- name: "Join worker"
  community.docker.docker_swarm:
    state: join
    timeout: 60
    advertise_addr: "{{ ansible_facts.enp0s8.ipv4.address }}"
    join_token: "{{ hostvars[groups['swarm_manager'][0]]['result_swarm_values']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ hostvars[groups['swarm_manager'][0]].ansible_host }}"
  when: inventory_hostname in groups['workers']
